import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// OrgSuspendedPage - Page shown when organization is suspended
// Date: 2026-01-13
import { Building2, Mail } from 'lucide-react';
import { useOrganization } from '@/hooks/useOrganization';
export default function OrgSuspendedPage() {
    const { currentOrg } = useOrganization();
    return (_jsx("div", { className: "min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 px-4", children: _jsxs("div", { className: "max-w-md w-full text-center", children: [_jsx("div", { className: "mb-8", children: _jsx("div", { className: "mx-auto w-24 h-24 bg-yellow-100 dark:bg-yellow-900/20 rounded-full flex items-center justify-center", children: _jsx(Building2, { className: "w-12 h-12 text-yellow-600 dark:text-yellow-400" }) }) }), _jsx("h1", { className: "text-3xl font-bold text-gray-900 dark:text-white mb-4", children: "Organiza\u00E7\u00E3o Suspensa" }), _jsxs("p", { className: "text-gray-600 dark:text-gray-400 mb-2", children: ["A organiza\u00E7\u00E3o ", _jsx("strong", { children: currentOrg?.name }), " est\u00E1 atualmente suspensa."] }), _jsx("p", { className: "text-gray-600 dark:text-gray-400 mb-8", children: "Entre em contato com o suporte para resolver esta situa\u00E7\u00E3o e reativar sua conta." }), _jsxs("div", { className: "bg-gray-100 dark:bg-gray-800 rounded-lg p-6 mb-8", children: [_jsx("h2", { className: "text-sm font-semibold text-gray-700 dark:text-gray-300 mb-4", children: "Informa\u00E7\u00F5es de Contato" }), _jsx("div", { className: "space-y-3 text-left", children: _jsxs("div", { className: "flex items-center text-gray-600 dark:text-gray-400", children: [_jsx(Mail, { className: "w-4 h-4 mr-3" }), _jsx("span", { children: "suporte@fartech.com.br" })] }) })] }), currentOrg?.plan === 'trial' && (_jsx("div", { className: "bg-blue-50 dark:bg-blue-900/20 rounded-lg p-4 text-sm text-blue-700 dark:text-blue-300", children: "Sua organiza\u00E7\u00E3o est\u00E1 em per\u00EDodo de teste. Entre em contato para ativar um plano." }))] }) }));
}
